[versions]
agp = "8.9.1"
apacheStringUtils = "3.20.0"
appcompat = "1.7.1"
blurhash = "0.3.0"
catppuccin = "0.1.2"
compileSdk = "36"
composeActivity = "1.12.2"
composeBom = "2025.12.01"
composeCompiler = "1.5.7"
composeGestures = "4.0.0"
composeJunit = "1.10.0"
coreKtx = "1.17.0"
crop = "0.1.1"
crypto = "1.1.0"
dayNightSwitch = "1.0.0"
exif = "1.4.2"
falClient = "0.7.1"
gson = "2.13.2"
junit = "4.13.2"
koin = "4.1.1"
koinCompose = "4.1.1"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.32" # Should match kotlin version
lifecycleViewModel = "2.10.0"
material = "1.13.0"
mediaPipeGenerator = "0.10.21"
minSdk = "24"
mockito = "2.2.0"
mockk = "1.14.7"
mvi = "1.0.2"
navigation = "2.9.6"
okhttp = "5.0.0-alpha.14"
onnx = "1.23.2"
paging = "3.1.1" # Do not upgrade!
pagingCompose = "1.0.0-alpha18" # Do not upgrade!
preferences = "1.0.1"
retrofit = "3.0.0"
roboelectric = "4.16"
room = "2.6.1"
rxAndroidVersion = "3.0.2"
rxJavaVersion = "3.1.12"
rxKotlinVersion = "3.0.1"
rxNetworkVersion = "4.0.0"
serialization = "1.9.0"
targetSdk = "34"
testCoroutines = "1.10.2"
timber = "5.0.1"
turbine = "1.2.1"
versionCode = "192"
versionName = "0.7.1"
workManager = "2.11.0"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-exif = { module = "androidx.exifinterface:exifinterface", version.ref = "exif" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewModel" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModel" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-rx = { module = "androidx.paging:paging-rxjava3", version.ref = "paging" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-rx = { module = "androidx.room:room-rxjava3", version.ref = "room" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "crypto" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workManager" }
apache-stringutils = { module = "org.apache.commons:commons-lang3", version.ref = "apacheStringUtils" }
blurhash = { module = "com.vanniktech:blurhash", version.ref = "blurhash" }
compose-crop = { module = "io.github.mr0xf00:easycrop", version.ref = "crop" }
compose-gestures = { module = "com.github.SmartToolFactory:Compose-Extended-Gestures", version.ref = "composeGestures" }
fal-client-kotlin = { module = "ai.fal.client:fal-client-kotlin", version.ref = "falClient" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-mediapipe-image-generator = { module = "com.google.mediapipe:tasks-vision-image-generator", version.ref = "mediaPipeGenerator" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
microsoft-onnx-runtime-android = { module = "com.microsoft.onnxruntime:onnxruntime-android", version.ref = "onnx" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit-adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rx-android = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxAndroidVersion" }
rx-java = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxJavaVersion" }
rx-kotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxKotlinVersion" }
rx-network = { module = "io.github.softartdev:reactivenetwork-rx3", version.ref = "rxNetworkVersion" }
shifthackz-catppuccin-compose = { module = "com.github.ShiftHackZ.Catppuccin-Android-Library:compose", version.ref = "catppuccin" }
shifthackz-catppuccin-legacy = { module = "com.github.ShiftHackZ.Catppuccin-Android-Library:palette-legacy", version.ref = "catppuccin" }
shifthackz-catppuccin-splash = { module = "com.github.ShiftHackZ.Catppuccin-Android-Library:splashscreen", version.ref = "catppuccin" }
shifthackz-daynightswitch = { module = "com.github.ShiftHackZ:DayNightSwitch", version.ref = "dayNightSwitch" }
shifthackz-mvi = { module = "com.github.ShiftHackZ:AndroidCoreMVI", version.ref = "mvi" }
shifthackz-preferences = { module = "com.github.ShiftHackZ:AndroidPreferences", version.ref = "preferences" }
test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeJunit" }
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeJunit" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "testCoroutines" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "testCoroutines" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-koin = { module = "io.insert-koin:koin-test", version.ref = "koin" }
test-koin-junit = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
test-mockito = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
generic-application = "generic.application:unspecified"
generic-baseline-profm = "generic.baseline.profm:unspecified"
generic-compose = "generic.compose:unspecified"
generic-flavors = "generic.flavors:unspecified"
generic-library = "generic.library:unspecified"
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
